[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gb = "CzwhX7PRyfdk8xGw2Wo4G8e7JtwQcatd42Do7AW5Fk2c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "make jest"
