use anchor_lang::prelude::*;

#[error_code]
pub enum ErrorCode {
    InsufficientFunds,
    InsufficientPrize,
    MaxFeeExceeded,
    PuzzleNotActive,
    InvalidPuzzleSolver,
    PuzzleTimedOut,
    PuzzleStillActive,
    NoPuzzleAttempts,
    PuzzleTransferNotApproved,
    InvalidVerifier,
    InvalidAdmin,
    InvalidCreator,
    PuzzleNotAttempted,
    InvalidFeeCalculation,
    InvalidSolver,
    PuzzleNotTimedOut,
    PuzzleStillInFinalTimer,
    InvalidMint,
    InvalidTokenOwner,
    InvalidBaseFeeAndMaxFee,
    InvalidMaxAttempts,
    InvalidBaseFee,
    InvalidMaxFee,
    InvalidAttemptTimeoutSeconds,
    InvalidAttemptFinalTimeoutSeconds,
    InvalidServiceFeeBps,
    InvalidEscrowTokenAccount,
    PuzzleFinalTimerTimedOut,
    PuzzleInAttemptedState,
}
